name: bagani
description: "A new Flutter project."
publish_to: 'none'

version: 0.1.2+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  http: ^1.2.2
  json_annotation: ^4.9.0
  go_router: ^14.6.2
  logging: ^1.3.0
  flutter_secure_storage: ^9.2.2
  curved_navigation_bar: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0

flutter:

  uses-material-design: true

  assets:
    - assets/img/app_icon.png