/// Maps model class names to human-friendly disease names for display.
const Map<String, String> kHumanFriendlyDiseaseNames = {
  'Apple___Apple_scab': 'Apple Scab',
  'Apple___Black_rot': 'Apple Black Rot',
  'Apple___Cedar_apple_rust': 'Cedar Apple Rust',
  'Apple___healthy': 'Healthy Apple Leaf',
  'Blueberry___healthy': 'Healthy Blueberry Leaf',
  'Cherry_(including_sour)___Powdery_mildew': 'Cherry Powdery Mildew',
  'Cherry_(including_sour)___healthy': 'Healthy Cherry Leaf',
  'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot': 'Corn Gray Leaf Spot',
  'Corn_(maize)___Common_rust_': 'Corn Common Rust',
  'Corn_(maize)___Northern_Leaf_Blight': 'Corn Northern Leaf Blight',
  'Corn_(maize)___healthy': 'Healthy Corn Leaf',
  'Grape___Black_rot': 'Grape Black Rot',
  'Grape___Esca_(Black_Measles)': 'Grape Black Measles (Esca)',
  'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)': 'Grape Leaf Blight',
  'Grape___healthy': 'Healthy Grape Leaf',
  'Orange___Haunglongbing_(Citrus_greening)': 'Citrus Greening (HLB)',
  'Peach___Bacterial_spot': 'Peach Bacterial Spot',
  'Peach___healthy': 'Healthy Peach Leaf',
  'Pepper,_bell___Bacterial_spot': 'Bell Pepper Bacterial Spot',
  'Pepper,_bell___healthy': 'Healthy Bell Pepper Leaf',
  'Potato___Early_blight': 'Potato Early Blight',
  'Potato___Late_blight': 'Potato Late Blight',
  'Potato___healthy': 'Healthy Potato Leaf',
  'Raspberry___healthy': 'Healthy Raspberry Leaf',
  'Soybean___healthy': 'Healthy Soybean Leaf',
  'Squash___Powdery_mildew': 'Squash Powdery Mildew',
  'Strawberry___Leaf_scorch': 'Strawberry Leaf Scorch',
  'Strawberry___healthy': 'Healthy Strawberry Leaf',
  'Tomato___Bacterial_spot': 'Tomato Bacterial Spot',
  'Tomato___Early_blight': 'Tomato Early Blight',
  'Tomato___Late_blight': 'Tomato Late Blight',
  'Tomato___Leaf_Mold': 'Tomato Leaf Mold',
  'Tomato___Septoria_leaf_spot': 'Tomato Septoria Leaf Spot',
  'Tomato___Spider_mites Two-spotted_spider_mite':
      'Tomato Two-spotted Spider Mite',
  'Tomato___Target_Spot': 'Tomato Target Spot',
  'Tomato___Tomato_Yellow_Leaf_Curl_Virus': 'Tomato Yellow Leaf Curl Virus',
  'Tomato___Tomato_mosaic_virus': 'Tomato Mosaic Virus',
  'Tomato___healthy': 'Healthy Tomato Leaf',
};
