// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace with your actual Firebase configuration

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmdH0Is-yuGC_mAYESyzwYOjer5G-kZZY',
    appId: '1:379042498017:web:9ec379719cd7362c0e3ea0',
    messagingSenderId: '379042498017',
    projectId: 'bagani-bd',
    authDomain: 'bagani-bd.firebaseapp.com',
    databaseURL: 'https://bagani-bd-default-rtdb.firebaseio.com',
    storageBucket: 'bagani-bd.firebasestorage.app',
  );

  // You can get these values from your Firebase console

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZS9VYuB3tUBKv6MsJc3LCRitMg5STmGI',
    appId: '1:379042498017:android:e1c41029f76a02df0e3ea0',
    messagingSenderId: '379042498017',
    projectId: 'bagani-bd',
    databaseURL: 'https://bagani-bd-default-rtdb.firebaseio.com',
    storageBucket: 'bagani-bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVV09VQ0MCDUPDu0YoYVY5hCuVbCjQTzw',
    appId: '1:379042498017:ios:db674ac537a82df80e3ea0',
    messagingSenderId: '379042498017',
    projectId: 'bagani-bd',
    databaseURL: 'https://bagani-bd-default-rtdb.firebaseio.com',
    storageBucket: 'bagani-bd.firebasestorage.app',
    iosBundleId: 'com.bagani.bagani',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVV09VQ0MCDUPDu0YoYVY5hCuVbCjQTzw',
    appId: '1:379042498017:ios:db674ac537a82df80e3ea0',
    messagingSenderId: '379042498017',
    projectId: 'bagani-bd',
    databaseURL: 'https://bagani-bd-default-rtdb.firebaseio.com',
    storageBucket: 'bagani-bd.firebasestorage.app',
    iosBundleId: 'com.bagani.bagani',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmdH0Is-yuGC_mAYESyzwYOjer5G-kZZY',
    appId: '1:379042498017:web:25b818542d8edd020e3ea0',
    messagingSenderId: '379042498017',
    projectId: 'bagani-bd',
    authDomain: 'bagani-bd.firebaseapp.com',
    databaseURL: 'https://bagani-bd-default-rtdb.firebaseio.com',
    storageBucket: 'bagani-bd.firebasestorage.app',
  );

}