name: bagani
description: "AI-Powered Plant Care Mobile Application - Disease Detection & Treatment Recommendations"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  water_drop_nav_bar: ^2.2.1
  lottie: ^3.1.2

  # State Management
  flutter_riverpod: ^2.5.1

  # Routing
  go_router: ^14.2.7

  # Network
  dio: ^5.4.3+1
  logger: ^2.4.0

  # TensorFlow Lite
  tflite_flutter: ^0.11.0

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: any

  # Utilities
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  camera: ^0.10.6
  image: ^4.1.7
  path: ^1.9.0
  
  # Database
  sqflite: ^2.3.3+1
  
  # Storage
  flutter_secure_storage: ^9.2.4
  
  # URL Launcher
  url_launcher: ^6.3.1
  
  # Package Info
  package_info_plus: ^8.0.2
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/models/
    - assets/care_guides.json
    
  generate: true
